# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41e021e6b9504b41fcfb1cbb51c081ca58f68de0cf21d13d80a25758173005f192cc6eb7014cbe41b7268e5495ad0a29a235eff0ea7bf187fa3abacb94937e17

test:
  secret_key_base: 68d3a56f6ed51bab3bf59f8ccdb8574233967e6f25ab624e14ea6c97a93a926f98d640c54db7de721eb0ad24f5e5a283d4d8aba9a0fb2802a6e0b5391b8d7782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
